# reload config after change: 
## tmux source ~/.tmux.conf

# rebind prefix key
set -g prefix C-a
unbind C-b
bind C-a send-prefix

# set copy mode keys to vim style
setw -g mode-keys vi   

# undscore the current window (or pane?)
set -g window-status-current-style 'underscore'

# put the status bar on the top
set -g status-position top

# vim style pane nav
unbind-key j
bind-key j select-pane -D
unbind-key k
bind-key k select-pane -U
unbind-key h
bind-key h select-pane -L
unbind-key l
bind-key l select-pane -R   

# set horizontal pane split to `-`

# set vertical pane split to `\`

